apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rdpf49538-python 
  janus-idp.io/tekton: rdpf49538-python
  backstage.io/kubernetes-id: rdpf49538-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rdpf49538-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml