apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rdpf49538-python-gitops
  description: This is GitOps manifest for rdpf49538-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rdpf49538-python
    backstage.io/kubernetes-id: rdpf49538-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-qe-jsmid/rdpf49538-python-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rdpf49538-python
